kind: Namespace
apiVersion: v1
metadata:
  name: wireguard
---
kind: Secret
apiVersion: v1
metadata:
  name: wg-secret
  namespace: wireguard
type: Opaque
data:
  # Generate and encode the server private key: `wg genkey | base64`
  privatekey: Mkc3K0NJalZ6a3NRWjd0RzJrYWlKZlE1OUJ6alpIdFBMaTVLemkvczZWVT0=
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: wg-configmap
  namespace: wireguard
data:
  wg0.conf: |
    [Interface]
    Address = 10.0.0.1/24
    ListenPort = 51820
    PostUp = wg set wg0 private-key /etc/wireguard/privatekey && iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostUp = printf "nameserver 10.90.0.5\nsearch default.svc.cluster.local svc.cluster.local cluster.local" | resolvconf -a %i
    PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    SaveConfig = true

    [Peer]
    PublicKey = zGqJG7CmMIEmztwt22/75oUOCtJTiYSUEKxj7zW0vU8=
    AllowedIPs = 192.168.1.4/32

    [Peer]
    PublicKey = ylJLmvdEhcWkegHUGkUvp8SHc5u54XTM/y6GwxE7pR0=
    AllowedIPs = 10.0.0.2/32
---
kind: Service
apiVersion: v1
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    app: wireguard
spec:
  type: LoadBalancer
  ports:
  - name: wg
    protocol: UDP
    port: 51820
    targetPort: 51820
  selector:
    app: wireguard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
        type: test
    spec:
      initContainers:
        - name: sysctls
          image: busybox
          command:
          - sh
          - -c
          - sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
      containers:
        - name: wireguard
          image: docker.io/alok78/wireguard-go:latest
          imagePullPolicy: Always
          command:
          - sh
          - -c
          - echo "Public key '$(wg pubkey < /etc/wireguard/privatekey)'" && /entrypoint.sh
          ports:
          - containerPort: 51820
            protocol: UDP
            name: wireguard
          env:
          - name: LOG_LEVEL
            value: info
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          resources:
            requests:
              memory: 64Mi
              cpu: "100m"
            limits:
              memory: 256Mi
          volumeMounts:
          - name: cfgmap
            mountPath: /etc/wireguard/wg0.conf
            subPath: wg0.conf
          - name: secret
            mountPath: /etc/wireguard/privatekey
            subPath: privatekey
        - name: hello-world
          image: bhargavshah86/kube-test:v0.1
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: 256Mi
              cpu: "250m"
            requests:
              memory: 128Mi
              cpu: "80m"
      volumes:
      - name: cfgmap
        configMap:
          name: wg-configmap
      - name: secret
        secret:
          secretName: wg-secret